### ISSUE TITLE
jit compile not working

### ISSUE THREAD

**Issue by jcbayley** [mj-will/bayesbeat#11]
I can't use the model function after its been jit compiled here:
https://github.com/mj-will/bayesbeat/blob/3ce8eef40017140b33c820ba99daa6b020d8eb58/src/bayesbeat/model/generic_analytic.py#L122

The input args seem to change from:
('B_1', 'B_2', 'C_0', 'C_1', 'C_2', 'C_3', 'dw', 'x_0')
to
('f',)

So I get an error:
TypeError: jit.<locals>.<lambda>() got an unexpected keyword argument 'B_1'

@mj-will have you come across this before? I cant seem to find an easy fix other than turning off the jit compilation.

**Comment by mj-will** [comment]
@jcbayley is this occurring when running the inference or at another point? I don't think the jit compilation supports keyword arguments, but everywhere in the code should be using positional arguments so I'm a bit confused where this error is coming from

**Comment by mj-will** [comment]
Scratch that, it does use keyword arguments. I've checked and I am using the JIT so I'm rather confused why this would be happening for you and not me. Do you have the ini file you're using?

**Comment by jcbayley** [comment]
Its appearing when the likelihood is first called. 
https://github.com/mj-will/bayesbeat/blob/3ce8eef40017140b33c820ba99daa6b020d8eb58/src/bayesbeat/analysis.py#L89

If it cant take in kwargs then I guess its these lines where there is a issue as self.func have kwargs as inputs? 
https://github.com/mj-will/bayesbeat/blob/3ce8eef40017140b33c820ba99daa6b020d8eb58/src/bayesbeat/model/generic_analytic.py#L211

 https://github.com/mj-will/bayesbeat/blob/3ce8eef40017140b33c820ba99daa6b020d8eb58/src/bayesbeat/model/generic_analytic.py#L245

Although if you haven't seen a problem here I'm also a little confused.

**Comment by jcbayley** [comment]
> Scratch that, it does use keyword arguments. I've checked and I am using the JIT so I'm rather confused why this would be happening for you and not me. Do you have the ini file you're using?

`
[General]
output = "./output_1"
label = "disk_0"
datafile = "../LS_SUS1/PyTotalAnalysis.mat"
indices = 0
seed = 1234
plot = True
injection = False

[Data]
rescale-amplitude = False
maximum-amplitude = None
sample-rate = None
duration = None

[Injection]

[Model]
name = GenericAnalyticGaussianBeam
equation_name = General_Equation_3_Terms
photodiode-size = 1e-2
photodiode-gap = 0.25e-3
n-terms = 3
include-gap = True
beam_radius = 1e-3
x_offset = 0.0
rin_noise = True
prior_bounds = {"a_ratio": [0, 1], 
                "tau_1": [290, 310], 
                "tau_2": [140, 160], 
                "dphi": [0, 3.141592654], 
                "domega": [0.18, 0.22], 
                "a_scale": [0, 10], 
                "sigma_noise": [0, 10.0]}


[Analysis]
n-pool = None
resume = True

[Sampler]
nlive = 1000
reset_flow = 8
`

**Comment by mj-will** [comment]
Ah, I think this is happening because you don't have `numba` installed. Are you getting a warning:

```
Could not import numba
```

It seems the hack I had to handle the case where numba is missing doesn't work.

**Comment by mj-will** [comment]
FWIW, the JIT compilation seems to reduce the log-likelihood time by a factor ~5 so it's definitely worth installing `numba` if you can.

**Comment by jcbayley** [comment]
Ahhhhh sorry, didn't spot that error, yeah thats fixed it. Thought I had it installed already.
